version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:55"
    labels:
      - "dependencies"
    groups:
      org-actions:
        applies-to: version-updates
        patterns: ["Coalfire-CF/*"]
        update-types: ["minor", "patch"]
      third-party:
        applies-to: version-updates
        patterns: ["*"]
        exclude-patterns: ["Coalfire-CF/*"]
        update-types: ["minor", "patch"]
