name: "CI: Terraform docs"
on:
    pull_request:
    workflow_call:

jobs:
  terraform-docs:
    uses: Coalfire-CF/Actions/.github/workflows/ci-terraform-docs.yml@6b75ed76d73064326039a5fd49fc962614c0f65d # v1.1.1
    with:
      find-dir: organization
