name: Org Terraform Docs
on:
    pull_request:
    workflow_call:

jobs:
  terraform-docs:
    uses: Coalfire-CF/Actions/.github/workflows/org-terraform-docs.yml@0324cf8a90b4b9c523465f53a892a722f613e318 # v0.15.0
    with:
      find-dir: organization