name: Org Terraform Docs
on:
    pull_request:
    workflow_call:

jobs:
  terraform-docs:
    uses: Coalfire-CF/Actions/.github/workflows/org-terraform-docs.yml@162d71ff9bace6c2994b3b8d9e5bfc33f6b54eed # v0.18.0
    with:
      find-dir: organization