name: Markdown Lint
on:
    pull_request:
      paths:
        - '**.md'
      branches:
        - main
    workflow_call:

jobs:
  check-markdown:
    uses: Coalfire-CF/Actions/.github/workflows/org-markdown-lint.yml@23c6c8bc526102ed041f2e08a363e5ea2c2f0ec4 # v0.18.1