name: Org Release
on:
    pull_request:
        types:
        - closed
        branches:
        - main

jobs:
  create-release:
    uses: Coalfire-CF/Actions/.github/workflows/org-release.yml@f1183271357ddaaa090a33c1b722133f874ef86d # v0.8.2