name: Markdown Lint
on:
    pull_request:
      paths:
        - '**.md'
      branches:
        - main
    workflow_call:

jobs:
  check-markdown:
    uses: Coalfire-CF/Actions/.github/workflows/org-markdown-lint.yml@df5fe1a0ee9068473c763609fc1d20c66df6ef94 # v0.14.0