name: Markdown Lint
on:
    pull_request:
      paths:
        - '**.md'
      branches:
        - main
    workflow_call:

jobs:
  check-markdown:
    uses: Coalfire-CF/Actions/.github/workflows/org-markdown-lint.yml@9451b979c22b3762b3c8a7d4d9493fefaee7edc5 # v0.11.3