name: Org Release
on:
    pull_request:
        types:
        - closed
        branches:
        - main

jobs:
  create-release:
    uses: Coalfire-CF/Actions/.github/workflows/org-release.yml@23c6c8bc526102ed041f2e08a363e5ea2c2f0ec4 # v0.18.1
    secrets: inherit
