name: "Release: Release Please"
on:
    pull_request:
        types:
        - closed
        branches:
        - main

jobs:
  create-release:
    uses: Coalfire-CF/Actions/.github/workflows/release-please.yml@6b75ed76d73064326039a5fd49fc962614c0f65d # v1.1.1
    secrets: inherit
