name: "Release: Release Please"
on:
    pull_request:
        types:
        - closed
        branches:
        - main

jobs:
  create-release:
    uses: Coalfire-CF/Actions/.github/workflows/release-please.yml@e63fdc45774e5963925b931238797256692cf040 # v1.2.0
    secrets: inherit
